version: '3'

services:
  db:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      JWT_SECRET: "${JWT_SECRET}"
      ALGORITHM: "${ALGORITHM}"
      BOT_TOKEN: "${BOT_TOKEN}"
    depends_on:
      - db
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"

  tg-bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    restart: always
    container_name: telegram-bot
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      JWT_SECRET: "${JWT_SECRET}"
      ALGORITHM: "${ALGORITHM}"
      BOT_TOKEN: "${BOT_TOKEN}"
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
volumes:
  postgres-data: